title: Guyren.me
description: > # this means to ignore newlines until "baseurl:"
  Personal thoughts of Guyren Howe
  
  This is the personal blog of Guyren Howe, where I will discuss matters mostly political, technological and philosophical.
  permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://guyren.me" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Guyren G Howe # add your name
author-img: guyren.jpg # add your photo
about-author: Developer (professionally)/philosopher (personally).
social-twitter: unclouded # add your Twitter handle
social-github: gisborne # add your Github handle
social-email: guyren@relevantlogic.com # add your Email address

# Disqus
discus-identifier: gisborne # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
